---
# handlers file for ansible-nsq

- name: reload daemon
  become: true
  command: systemctl daemon-reload

- name: restart nsqd
  become: true
  service: name=nsqd state=restarted enabled=yes

- name: restart nsqlookupd
  become: true
  service: name=nsqlookupd state=restarted enabled=yes
