{
 "title": "NSQ Bench",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Host Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) * -100 + 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes/node_memory_MemTotal_bytes*100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[$__rate_interval])",
     "legendFormat": "{{instance}} rx"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[$__rate_interval])",
     "legendFormat": "{{instance}} tx"
    }
   ]
  },
  { "title": "NSQ Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "NSQ RR Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "nsq_topic_sub_1_channel_rr_clients + nsq_topic_sub_2_channel_rr_clients + nsq_topic_sub_3_channel_rr_clients + nsq_topic_sub_4_channel_rr_clients + nsq_topic_sub_5_channel_rr_clients + nsq_topic_sub_6_channel_rr_clients + nsq_topic_sub_7_channel_rr_clients + nsq_topic_sub_8_channel_rr_clients + nsq_topic_sub_9_channel_rr_clients + nsq_topic_sub_10_channel_rr_clients + nsq_topic_sub_11_channel_rr_clients + nsq_topic_sub_12_channel_rr_clients + nsq_topic_sub_13_channel_rr_clients",
     "legendFormat": "{{instance}} combined rr clients"
    }
   ]
  },
  {
   "title": "NSQ RR Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(nsq_topic_sub_1_channel_rr_message_count[$__rate_interval]) + rate(nsq_topic_sub_2_channel_rr_message_count[$__rate_interval]) + rate(nsq_topic_sub_3_channel_rr_message_count[$__rate_interval]) + rate(nsq_topic_sub_4_channel_rr_message_count[$__rate_interval]) + rate(nsq_topic_sub_5_channel_rr_message_count[$__rate_interval]) + rate(nsq_topic_sub_6_channel_rr_message_count[$__rate_interval]) + rate(nsq_topic_sub_7_channel_rr_message_count[$__rate_interval]) + rate(nsq_topic_sub_8_channel_rr_message_count[$__rate_interval]) + rate(nsq_topic_sub_9_channel_rr_message_count[$__rate_interval]) + rate(nsq_topic_sub_10_channel_rr_message_count[$__rate_interval]) + rate(nsq_topic_sub_11_channel_rr_message_count[$__rate_interval]) + rate(nsq_topic_sub_12_channel_rr_message_count[$__rate_interval]) + rate(nsq_topic_sub_13_channel_rr_message_count[$__rate_interval])",
     "legendFormat": "{{instance}} rr messages"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "nsq_topic_sub_1_depth + nsq_topic_sub_2_depth + nsq_topic_sub_3_depth + nsq_topic_sub_4_depth + nsq_topic_sub_5_depth + nsq_topic_sub_6_depth + nsq_topic_sub_7_depth + nsq_topic_sub_8_depth + nsq_topic_sub_9_depth + nsq_topic_sub_10_depth + nsq_topic_sub_11_depth + nsq_topic_sub_12_depth + nsq_topic_sub_13_depth",
     "legendFormat": "combined topic depth {{instance}}"
    },
    {
     "expr": "nsq_topic_sub_1_channel_rr_backend_depth + nsq_topic_sub_2_channel_rr_backend_depth + nsq_topic_sub_3_channel_rr_backend_depth + nsq_topic_sub_4_channel_rr_backend_depth + nsq_topic_sub_5_channel_rr_backend_depth + nsq_topic_sub_6_channel_rr_backend_depth + nsq_topic_sub_7_channel_rr_backend_depth + nsq_topic_sub_8_channel_rr_backend_depth + nsq_topic_sub_9_channel_rr_backend_depth + nsq_topic_sub_10_channel_rr_backend_depth + nsq_topic_sub_11_channel_rr_backend_depth + nsq_topic_sub_12_channel_rr_backend_depth + nsq_topic_sub_13_channel_rr_backend_depth",
     "legendFormat": "combined rr queue depth {{instance}}"
    }
   ]
  }
 ]
}