common_monitoring_components:
  - statsd_exporter
  - node_exporter

prometheus_server_cfg:
  global:
    scrape_interval: 10s

  # A scrape configuration containing exactly one endpoint to scrape:
  # Here it's Prometheus itself.
  scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:9090']
    - job_name: 'node'
      scrape_interval: 5s
      static_configs:
        - targets: |
              [{% for host in hostvars -%} "{{ host }}:9100", {% endfor -%}]
    - job_name: 'statsd'
      scrape_interval: 5s
      static_configs:
        - targets: |
              [{% for host in hostvars -%} "{{ host }}:9102", {% endfor -%}]
