version: "3.8"

x-base: &base
  build: .
  ulimits: # expecting high numbers of connections
    nofile:
      soft: 20_000
      hard: 40_000

services:
  nsqlookupd:
    <<: *base
    command: /nsqlookupd

  nsq-a:
    <<: *base
    command: ['/nsqd', '--lookupd-tcp-address=nsqlookupd:4160']

  nsq-b:
    <<: *base
    command: ['/nsqd', '--lookupd-tcp-address=nsqlookupd:4160']
  nsq-c:
    <<: *base
    command: ['/nsqd', '--lookupd-tcp-address=nsqlookupd:4160']

  nsqadmin:
    image: nsqio/nsq
    command: ['/nsqadmin', '--lookupd-http-address=nsqlookupd:4161']
    ports:
      - 4171:4171

