---
- name: Install nsqlookupd systemd service
  become: true
  template:
    src: nsqlookupd.service.j2
    dest: /etc/systemd/system/nsqlookupd.service
  notify:
    - reload daemon
    - restart nsqlookupd
